### ISSUE TITLE
unexpected word split when encountering "3-inch"

### ISSUE THREAD

**Issue by Robwiebe** [unfoldingWord/string-punctuation-tokenizer#41]
The tokenizer correctly keeps words separated by a single dash (like “goat-hair” Exodus 26:7 NLT 2007), however we discovered that it splits up words when the dash is surrounded by a number and a word (like “3-inch” Exodus 25:25 NLT 2007). Is there a way for us to keep that as a single word?

**Comment by klappy** [comment]
Should be addressed in the latest release, `2.0.0-rc.1`. I've added tests in the codebase to ensure this works the way intended and so that it doesn't get broken in the future.

Try it out here: 
https://unfoldingword.github.io/string-punctuation-tokenizer/#/Tokenize

**Comment by klappy** [comment]
@Robwiebe I'm closing this issue and if we have any issues we can reopen it.
