### ISSUE TITLE
"½" character removed from word split

### ISSUE THREAD

**Issue by Robwiebe** [unfoldingWord/string-punctuation-tokenizer#42]
The tokenizer doesn’t count fraction characters (i’m guessing it considers it punctuation because I choose not to include punctuation). For example, “7½ feet wide” is split up into 3 words: “7", “feet”, “wide”. Is there a way for us to keep the “½” character together with the “7" like this "7½"? See Exodus 27:1 NLT 2007.

**Comment by klappy** [comment]
Should be addressed in the latest release, `2.0.0-rc.1`. I've added tests in the codebase to ensure this works the way intended and so that it doesn't get broken in the future.

Try it out here: 
https://unfoldingword.github.io/string-punctuation-tokenizer/#/Tokenize

**Comment by klappy** [comment]
@Robwiebe I'm closing this issue and if we have any issues we can reopen it.
