### ISSUE TITLE
Invalid date on installed app.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/string-punctuation-tokenizer#45]
See problem with date of app after install.  Since it is so old, could this be the build date of the electron module?

![Screen Shot 2020-04-03 at 11 43 27 AM](https://user-images.githubusercontent.com/14238574/78379516-7c5e6680-75a0-11ea-941a-83bcc309b473.png)

**Comment by klappy** [comment]
This issue may be created in the wrong repo :)

**Comment by PhotoNomad0** [comment]
Yeah, my fault - will try again @klappy

**Comment by PhotoNomad0** [comment]
This was in wrong repo
