### ISSUE TITLE
Normalize Hebrew strings for canonical equivalence according to Unicode standard

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/string-punctuation-tokenizer#50]
see SPIKE:  #46
Based on https://unicode.org/reports/tr15/#Canonical_Equivalence and following. Note that: The outputs are not required to be identical, only canonically equivalent.

DoD: Opening resources with Hebrew words that have been identified as edge cases and should be highlighted

@ancientTexts-net please add list of edge cases.

**Comment by ancientTexts-net** [comment]
all UHB cases have been written as demos in `scripture-resources-rcl`.
(rewritten from the spike using Cecil's new hooks/contexts)

**Comment by ancientTexts-net** [comment]
passed in QA: tC Create v `1.0.3.rc-2`
