### ISSUE TITLE
Normalize Greek strings for canonical equivalence according to Unicode standard

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/string-punctuation-tokenizer#51]
see SPIKE: #46
Based on https://unicode.org/reports/tr15/#Canonical_Equivalence and following. Note that: The outputs are not required to be identical, only canonically equivalent.

DoD: Opening resources with Greek words that have been identified as edge cases and should be highlighted

@ancientTexts-net please add list of Greek edge cases.

**Comment by ancientTexts-net** [comment]
can be QA in the RCL:

plesae note that even when we specify a `selection` that is NOT initially equivalent to the uW alignments, the `selection` is highlighted after normalization.  (No user data is normalized.  Only the original language alignment && the comparison is normalized.)

(NOTE: takes this demo a long time to fully load the ParallelScripture panes)

https://deploy-preview-43--scripture-resources-rcl.netlify.app/#/Unicode%20Encoding%20%26%20Normalization?id=section-hebrew-cases

**Comment by ancientTexts-net** [comment]
passed in QA: tC Create v `1.0.3.rc-2`
